name: Push Actions
on:
  workflow_call:
  # Triggers the workflow on push
  # push:
  #   branches: [develop, stage, preview, main, previous]

jobs:
  api_validator:
    uses: ./.github/workflows/github-yaml-validator.yaml
    secrets: inherit
  api-zip-generator:
    needs: api_validator
    uses: ./.github/workflows/github-zip-generator.yaml
    if: ${{!contains(needs.api_validator.outputs.statuscheck, 'SKIPPED')}}
    secrets: inherit
  webhook-retrigger:
    uses: ./.github/workflows/retrigger-failed-webhook.yaml
    secrets: inherit
