name: Markdown Linter
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      statuscheck:
        description: "Output of markdown validation job"
        value: ${{ jobs.markdown-linter.outputs.job_status }}

jobs:
  markdown-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      job_status: ${{ steps.markdown_lint.outputs.status }}
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Run Markdown linter
        id: markdown_lint
        uses: Fiserv/remote-actions/actions/run-node-script@main
        with:
          display-name: Markdown linter
          script-command: markdownlint ${{ github.workspace }}
      - name: Cleanup tools directory
        if: always()
        uses: Fiserv/remote-actions/actions/cleanup-tools@main
      - run: echo "🍏 This job's status is ${{ job.status }} and output - ${{ steps.markdown_lint.outputs.status }}"
