name: Markdown Validator
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      statuscheck:
        description: "Output of markdown validation job"
        value: ${{ jobs.markdown-validator.outputs.job_status }}

jobs:
  markdown-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      job_status: ${{ steps.markdown_validate.outputs.status }}
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Run Markdown validator
        id: markdown_validate
        uses: Fiserv/remote-actions/actions/run-node-script@main
        with:
          display-name: Markdown validator
          script-command: markdown ${{ github.workspace }}
      - name: Cleanup tools directory
        if: always()
        uses: Fiserv/remote-actions/actions/cleanup-tools@main
