name: Tenant Config Validator
on:
  workflow_call:

jobs:
  tenant-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Run tenant config validator
        uses: Fiserv/remote-actions/actions/run-node-script@main
        with:
          display-name: tenant config validator
          script-command: configcheck ${{ github.workspace }} ${{ vars.FISERV_INTERNAL }}
      - name: Cleanup tools directory
        if: always()
        uses: Fiserv/remote-actions/actions/cleanup-tools@main
