name: Markdown Validator
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      statuscheck:
        description: "Output of markdown validation job"
        value: ${{ jobs.markdown-validator.outputs.job_status }}

jobs:
  markdown-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      job_status: ${{ steps.markdown_validate.outputs.JobStatus }}
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@main
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/.dev-studio-tools/scripts/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Running Markdown Validator.....
        id: markdown_validate
        run: |
          cd ${{ github.workspace }}/.dev-studio-tools/scripts
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm ci
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          result=$(npm run markdown ${{ github.workspace }})
          echo "**********TEST RESULTS*********************"
          echo "$result"
          if [[ $result == *'FAILED'* ]] ;then
            echo "Validator failed and exiting the Job..."
            exit 1
          elif [[ $result == *'PASSED'* ]] ;then
            echo "Validator Ran Successfully....🍏"
          fi
      - run: echo "🍏 This job's status is ${{ job.status }} and output - ${{ steps.markdown_validate.outputs.JobStatus }}"
