name: YAML Validator
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      statuscheck:
        description: "Output of YAML validation job"
        value: ${{ jobs.yaml-validator.outputs.output1 }}

jobs:
  yaml-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      output1: ${{ steps.yamlvalidate.outputs.status }}
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Run YAML validator
        id: yamlvalidate
        uses: Fiserv/remote-actions/actions/run-node-script@main
        with:
          display-name: YAML validator
          script-command: validate ${{ github.workspace }}
        # env:
        #   GH_TOKEN: ${{ secrets.ZIP_GENERATOR_ACTION }}
      - name: Cleanup tools directory
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/.dev-studio-tools
          echo "Temp tools directory deleted ......"
      - run: echo "🍏 This job's status is ${{ job.status }} and output - ${{ steps.yamlvalidate.outputs.status }}"
