name: Release Notes Validator
on:
  workflow_call:

jobs:
  release-notes-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Run release notes validator
        uses: Fiserv/remote-actions/actions/run-node-script@main
        with:
          display-name: release notes validator
          script-command: releasenotes ${{ github.workspace }}
      - name: Cleanup tools directory
        if: always()
        uses: Fiserv/remote-actions/actions/cleanup-tools@main
