name: TenantConfig Validator
on:
  workflow_call:
    inputs:
      fr-tenant:
        description: 'Variable specifically for Fiserv Resources tenants'
        required: false
        default: false
  push:
    branches: [ develop,stage,preview,main,previous ]
    paths:
      - 'config/**'     
  pull_request:
    branches: [ develop,stage,preview,main,previous ]
    paths:
      - 'config/**' 

jobs:
  Tenant-Config-Action:
    runs-on: ubuntu-latest
    timeout-minutes: 15    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}." 
      - name: Creating new temp sub dir called `tools`
        run: |
         mkdir -m 777 tools
         cd tools
         pwd
         ls -la
      - name: Check out ${{ github.repository }} Repo code at ${{ github.workspace }}
        uses: actions/checkout@v3
        with:
         repository: ${{ github.repository }}
         path: ${{ github.workspace }}
      - name: Check out Fiserv/remote-actions Repo code at ${{ github.workspace }}/tools
        uses: actions/checkout@v3
        with:
         repository: Fiserv/remote-actions
         ref: PORT-10030-Solution-Validator
         path: ${{ github.workspace }}/tools
      - name: List files in the repository
        run: |
         cd ${{ github.workspace }}
         pwd
         ls -la
         cd ${{ github.workspace }}/tools
         pwd
         ls -la
      - run: echo "💡 The ${{ github.repository }} repository has been cloned on root"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
         pwd
         ls -la

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Running Tenant Config Validator.....
        run: |
          pwd
          cd ${{ github.workspace }}/tools/scripts
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm install
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          if [[ ${{ github.event.inputs.fr-tenant }} ]]; then
            echo "Executing 'npm run configcheck ${{github.workspace }} true'"
            result=$(npm run configcheck ${{github.workspace }} true)
          else
            echo "Executing 'npm run configcheck ${{github.workspace }}'"
            result=$(npm run configcheck ${{github.workspace }})
          fi
          echo "**********TEST RESULTS*********************"
          echo "$result"
          pwd
          ls -la
          rm -rf ${{github.workspace }}/tools
          echo "Temp tools directory deleted ......"
          if [[ $result == *'VALIDATOR FAILED'* ]] ;then
          echo "Validator failed and exiting the Job..."
          exit 1
          elif [[ $result == *'PASSED'* ]] ;then
          echo "Validator Ran Successfully....🍏"
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Show file content
        run: |
          pwd
          ls -la
      # - name: Commited changes from action runner to remote branch
      #   uses: stefanzweifel/git-auto-commit-action@v4