name: API Specs Validator
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      statuscheck:
        description: "Output of Api validation job"
        value: ${{ jobs.api_validator_actions.outputs.output1 }}
  # push:
  #   branches: [develop, stage, preview, main, previous]
  #   paths:
  #     - "reference/**"
  # pull_request:
  #   branches: [develop, stage, preview, main, previous]
  #   paths:
  #     - "reference/**"

jobs:
  api_validator_actions:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      output1: ${{ steps.apivalidate.outputs.JobStatus }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and ${GITHUB_REF##*/} and ${GITHUB_REF#refs/heads/} and your repository is ${{ github.repository }}."
      - name: Creating new temp sub dir called `tools`
        run: |
          mkdir -m 777 tools
          cd tools
          pwd
          ls -la
      - name: Check out ${{ github.repository }} Repo code at ${{ github.workspace }}
        uses: actions/checkout@main
        with:
          repository: ${{ github.repository }}
          path: ${{ github.workspace }}
      - name: Check out Fiserv/remote-actions Repo code at ${{ github.workspace }}/tools
        uses: actions/checkout@main
        with:
          repository: Fiserv/remote-actions
          ref: main
          path: ${{ github.workspace }}/tools
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -la
          cd ${{ github.workspace }}/tools
          pwd
          ls -la
      - run: echo "💡 The ${{ github.repository }} repository has been cloned on root"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          pwd
          ls -la

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@main
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Running API Specs Validator.....
        id: apivalidate
        run: |
          pwd
          cd ${{ github.workspace }}/tools/scripts
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm install
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          result=$(npm run validate ${{github.workspace }})
          echo "**********TEST RESULTS*********************"
          echo "$result"
          pwd
          ls -la
          rm -rf ${{github.workspace }}/tools
          echo "Temp tools directory deleted ......"
          if [[ $result == *'VALIDATOR FAILED'* ]] ;then
            echo "Validator failed and exiting the Job..."
            exit 1 
          elif [[ $result == *'PASSED'* ]] ;then
            echo "Validator Ran Successfully....🍏" 
          elif [[ $result == *'SKIPPED'* ]] ;then
            echo "Validator JOB IS SKIPPED"
            echo "JobStatus="$result >> $GITHUB_OUTPUT                    
          fi
        # env:
        #   GH_TOKEN: ${{ secrets.ZIP_GENERATOR_ACTION }}
      - run: echo "🍏 This job's status is ${{ job.status }} and output - ${{ steps.apivalidate.outputs.JobStatus }}"
