name: Remove Inactive Users

on:
  schedule:
  - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering
    inputs:
      excluded_members:
        description: 'Comma-separated list of members to exclude'
        required: false
        default: ''

jobs:
  remove-inactive-users:
    runs-on: ubuntu-latest

    steps:

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Debug ORG_MEMBER
        run: |
          ORG_NAME="Fiserv"
          GITHUB_API_URL="https://api.github.com"
          TOKEN=${{ secrets.CLEANUP_TOKEN }}
          ORG_MEMBERS=$(curl -s -H "Authorization: token $TOKEN" "$GITHUB_API_URL/orgs/$ORG_NAME/members")
          echo "Organization Members:"
          for MEMBER in $(echo "$ORG_MEMBERS" | jq -r '.[].login'); do
            echo "- $MEMBER"
          done

      - name: Fetch team members and their contributions
        id: fetch_contributions
        run: |
          GITHUB_API_URL="https://api.github.com"
          ORG_NAME="Fiserv"
          EXCLUDED_TEAMS=("developer-studio-admin" "developer-studio-test" "developer-studio-support" "cloud-acceleration-center") # Teams to be excluded
          EXCLUDED_MEMBERS=("tomeck" "pavanjoshi12") # Specific users to be excluded
          INPUT_EXCLUDED_MEMBERS="${{ github.event.inputs.excluded_members }}"
          TOKEN=${{ secrets.CLEANUP_TOKEN }}
          THIRTY_DAYS_AGO=$(date --date='30 days ago' +"%Y-%m-%dT%H:%M:%SZ")
          REMOVED_MEMBERS_FILE="removed_members.txt"
          touch $REMOVED_MEMBERS_FILE

          # Convert the comma-separated string to an array
          IFS=',' read -r -a INPUT_EXCLUDED_MEMBERS_ARRAY <<< "$INPUT_EXCLUDED_MEMBERS"

          # Combine the hardcoded and input excluded members
          EXCLUDED_MEMBERS=("${EXCLUDED_MEMBERS[@]}" "${INPUT_EXCLUDED_MEMBERS_ARRAY[@]}")

          # Function to URL-encode team names to handle spaces
          url_encode() {
            echo "$1" | jq -sRr @uri
          }

          # Get the list of all members of the organization
          PAGE=1
          ORG_MEMBERS=""
          while [ $PAGE -lt 5 ]; do
            RESPONSE=$(curl -s -H "Authorization: token $TOKEN" "$GITHUB_API_URL/orgs/$ORG_NAME/members?role=member&per_page=100&page=$PAGE")
            if [ "$(echo "$RESPONSE" | jq length)" -eq 0 ]; then
              break
            fi
            ORG_MEMBERS="$ORG_MEMBERS$(echo "$RESPONSE" | jq -c '.[]')"
            PAGE=$((PAGE + 1))
          done
          ORG_MEMBERS=$(echo "$ORG_MEMBERS" | jq -s '.')

          # Get members of the excluded teams
          EXCLUDED_TEAM_MEMBERS=()
          for TEAM in "${EXCLUDED_TEAMS[@]}"; do
            TEAM_MEMBERS=$(curl -s -H "Authorization: token $TOKEN" "$GITHUB_API_URL/orgs/$ORG_NAME/teams/$TEAM/members")
            EXCLUDED_TEAM_MEMBERS+=($(echo "$TEAM_MEMBERS" | jq -r '.[] | .login'))
          done

          # Get unique list of all excluded members (from teams and specific members)
          ALL_EXCLUDED_MEMBERS=($(printf "%s\n" "${EXCLUDED_TEAM_MEMBERS[@]}" "${EXCLUDED_MEMBERS[@]}" | sort -u))

          # Get recent activity for each member
          for MEMBER in $(echo "$ORG_MEMBERS" | jq -r '.[].login'); do
            echo "- $MEMBER"
            # Skip if the member is in the excluded list
            if [[ " ${ALL_EXCLUDED_MEMBERS[@]} " =~ " ${MEMBER} " ]]; then
              echo "$MEMBER is excluded, skipping..."
              continue
            fi

            # Fetch user's 10 most recent events
            USER_EVENTS=$(curl -s -H "Authorization: token $TOKEN" "$GITHUB_API_URL/users/$MEMBER/events?per_page=10")

            LAST_CONTRIBUTION=$(echo "$USER_EVENTS" | jq -r ".[] | select(.created_at > \"$THIRTY_DAYS_AGO\") | .created_at" | sort -r | head -n 1)

            if [ -z "$LAST_CONTRIBUTION" ]; then
              echo "$MEMBER has been inactive for over 30 days, removing..."
              curl -X DELETE -H "Authorization: token $TOKEN" "$GITHUB_API_URL/orgs/$ORG_NAME/memberships/$MEMBER"
              echo "$MEMBER" >> "$REMOVED_MEMBERS_FILE"
            else
              echo "$MEMBER has contributed recently: $LAST_CONTRIBUTION"
            fi
          done
          REMOVED_USERS=$(cat $REMOVED_MEMBERS_FILE)
          echo "USERS=$REMOVED_USERS" >> $GITHUB_ENV

      - name: Cleanup Summary
        run: |
          echo "Removed members: $USERS"
          echo "Cleanup complete!"
        env:
          USERS: ${{ env.USERS }}
