name: Webhook Failed Retry
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code and tools
        uses: Fiserv/remote-actions/actions/checkout-code-and-tools@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r ${{ github.workspace }}/.dev-studio-tools/.github/workflows/requirements.txt
      - name: Run Python script
        env:
          TEST_GITHUB_AUTH_TOKEN: ${{ secrets.TEST_GITHUB_AUTH_TOKEN }}
        run: python ${{ github.workspace }}/.dev-studio-tools/scripts/RedeliverWebhooks.py ${{ github.repository }}
