name: Tenant Validator
on:
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the dev, stage and main branch
  push:
    branches: [ develop,stage,preview,main ]
  pull_request:
    #branches: [ develop,stage,preview,main ]
    types: [opened , reopened]
   
jobs:
  api_validator: 
    uses: ./.github/workflows/github-yaml-validator.yaml
    if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/preview') || (github.ref == 'refs/heads/main')) }}
    secrets: inherit
  api-zip-generator:
    needs: api_validator
    uses: ./.github/workflows/github-zip-generator.yaml
    if: ${{ !contains( needs.api_validator.outputs.statuscheck , 'SKIPPED') && ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main')) }}
    secrets: inherit         
  tenant-config-validator: 
    uses: ./.github/workflows/github-tenant-config-validator.yaml
    #if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/preview') || (github.ref == 'refs/heads/main')) }}
      
