name: Tenant Validator
on:
  workflow_call:
  # branches are specified for 'push' and 'pull' triggers to enable local testing
  # (modify files in this repo instead of having to modify other repo's)
  # The workflow trigger happens regardless of the branches included in the 'push'
  # and 'pull' request triggers.
  push:
    branches: [ develop,stage,preview,main,previous ]
  pull_request:
    types: [opened , reopened]
   
jobs:
  api_validator: 
    uses: ./.github/workflows/github-yaml-validator.yaml 
    secrets: inherit
  api-zip-generator:
    needs: api_validator
    uses: ./.github/workflows/github-zip-generator.yaml
    if: ${{ !contains( needs.api_validator.outputs.statuscheck , 'SKIPPED') }}
    secrets: inherit         
  tenant-config-validator: 
    uses: ./.github/workflows/github-tenant-config-validator.yaml
  webhook-retrigger:
    uses: ./.github/workflows/retrigger-failed-webhook.yaml
    secrets: inherit 
