name: Tenant Validator
on:
  workflow_call:
    inputs:
      FR_tenant:
        description: 'Variable specifically for Fiserv Resources tenants'
  # Triggers the workflow on push or pull request events but only for the dev, stage, main, preview, and previous branches
  push:
    branches: [ develop,stage,preview,main,previous ]
  pull_request:
    branches: [ develop,stage,preview,main,previous ]
    types: [opened , reopened]
   
jobs:
  api_validator: 
    uses: ./.github/workflows/github-yaml-validator.yaml 
    secrets: inherit
  api-zip-generator:
    needs: api_validator
    uses: ./.github/workflows/github-zip-generator.yaml
    if: ${{ !contains( needs.api_validator.outputs.statuscheck , 'SKIPPED') && github.event_name == 'push' }}
    secrets: inherit         
  tenant-config-validator: 
    uses: ./.github/workflows/github-tenant-config-validator.yaml
    with:
      FR_tenant : ${{ github.event.inputs.FR_tenant }}
  webhook-retrigger:
    uses: ./.github/workflows/retrigger-failed-webhook.yaml
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
