name: Tenant Validator
on:
  workflow_call:
  # Triggers the workflow on pull request
  # pull_request:
  #   branches: [develop, stage, preview, main, previous]
  #   types: [opened, reopened]

jobs:
  api_validator:
    uses: ./.github/workflows/github-yaml-validator.yaml
    secrets: inherit
  doc_validator:
    uses: ./.github/workflows/github-md-validator.yaml
    secrets: inherit
  tenant-config-validator:
    uses: ./.github/workflows/github-tenant-config-validator.yaml
    secrets: inherit
  file-access-validator:
    uses: ./.github/workflows/github-file-access-validator.yaml
